git:
  depth: 10
language: node_js
cache: yarn
node_js:
  - '10'
  - '8'

before_script:
  - yarn bootstrap
  - yarn build

script:
  - yarn coverage --ci --maxWorkers=4 --no-cache

after_success:
  - yarn coverage-ci

stages:
  - lint
  - test
#  - name: publish
#    if: repo = ark120202/babel-lua
#      AND branch = master
#      AND type = push

jobs:
  include:
    - stage: lint
      node_js: '10'
      script: yarn lint
#    - stage: publish
#      node_js: '8'
#      script: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
#      deploy:
#        provider: script
#        script: npm run publish-master
#        skip_cleanup: true
#        on:
#          condition: '! $TRAVIS_COMMIT_MESSAGE =~ \[skip\ publish\]'
