export const builtins = new Map([
  // ['Symbol', 'symbol'],
  // ['Promise', 'promise'],
  // ['Map', 'map'],
  // ['WeakMap', 'weak-map'],
  // ['Set', 'set'],
  // ['WeakSet', 'weak-set'],
  // ['Observable', 'observable'],
  // ['setImmediate', 'set-immediate'],
  // ['clearImmediate', 'clear-immediate'],
  // ['asap', 'asap'],
  // ['Array', 'array'],
  // ['JSON', 'json'],
  // ['Object', 'object'],
  ['Math', 'math'],
  // ['Date', 'date'],
  // ['global', '_G'],
  // ['String', 'string'],
  // ['Number', 'number'],
  // ['Function', 'function'],
  // ['parseFloat', 'parse-float'],
  // ['parseInt', 'parse-int'],
]);
