_G.global = _G;
import './builtins/function';
import './builtins/symbol';
import './builtins/string';
import './builtins/console';
import './builtins/globals';
import './builtins/array';
import './builtins/set';
import './builtins/map';
import './builtins/math';
import './builtins/object';
import './builtins/reflect';
if (_VERSION === 'Lua 5.3') require('./builtins/arshift_53');
